# Generated by Django 3.0.5 on 2020-11-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.TextField(default='', max_length=100)),
                ('room', models.TextField(default='', max_length=100)),
                ('checkinday', models.TextField(default='', max_length=100)),
                ('checkoutday', models.TextField(default='', max_length=100)),
                ('name', models.TextField(default='', max_length=100)),
                ('id_number', models.TextField(default='', max_length=100)),
                ('email', models.TextField(default='', max_length=100)),
                ('phone', models.TextField(default='', max_length=100)),
                ('current_address', models.TextField(default='', max_length=100)),
                ('hotel_name', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=100)),
                ('capacity', models.TextField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
